/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupGuideRouteImport } from './routes/setup-guide'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileIosRouteImport } from './routes/mobile.ios'
import { Route as MobileAndroidRouteImport } from './routes/mobile.android'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedLicensesRouteImport } from './routes/_authenticated/licenses'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicRemoteStreamRouteImport } from './routes/api/public/remote/stream'
import { Route as ApiPublicRemoteStartRouteImport } from './routes/api/public/remote/start'
import { Route as ApiPublicRemoteRegisterRouteImport } from './routes/api/public/remote/register'
import { Route as ApiPublicRemotePendingRouteImport } from './routes/api/public/remote/pending'
import { Route as ApiPublicRemoteAcceptRouteImport } from './routes/api/public/remote/accept'

const SetupGuideRoute = SetupGuideRouteImport.update({
  id: '/setup-guide',
  path: '/setup-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIosRoute = MobileIosRouteImport.update({
  id: '/mobile/ios',
  path: '/mobile/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAndroidRoute = MobileAndroidRouteImport.update({
  id: '/mobile/android',
  path: '/mobile/android',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicensesRoute = AuthenticatedLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRemoteStreamRoute = ApiPublicRemoteStreamRouteImport.update({
  id: '/api/public/remote/stream',
  path: '/api/public/remote/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRemoteStartRoute = ApiPublicRemoteStartRouteImport.update({
  id: '/api/public/remote/start',
  path: '/api/public/remote/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRemoteRegisterRoute = ApiPublicRemoteRegisterRouteImport.update({
  id: '/api/public/remote/register',
  path: '/api/public/remote/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRemotePendingRoute = ApiPublicRemotePendingRouteImport.update({
  id: '/api/public/remote/pending',
  path: '/api/public/remote/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRemoteAcceptRoute = ApiPublicRemoteAcceptRouteImport.update({
  id: '/api/public/remote/accept',
  path: '/api/public/remote/accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRoute
  '/download': typeof DownloadRoute
  '/employee': typeof EmployeeRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/setup-guide': typeof SetupGuideRoute
  '/app': typeof AuthenticatedAppRoute
  '/licenses': typeof AuthenticatedLicensesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/mobile/android': typeof MobileAndroidRoute
  '/mobile/ios': typeof MobileIosRoute
  '/api/public/remote/accept': typeof ApiPublicRemoteAcceptRoute
  '/api/public/remote/pending': typeof ApiPublicRemotePendingRoute
  '/api/public/remote/register': typeof ApiPublicRemoteRegisterRoute
  '/api/public/remote/start': typeof ApiPublicRemoteStartRoute
  '/api/public/remote/stream': typeof ApiPublicRemoteStreamRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRoute
  '/download': typeof DownloadRoute
  '/employee': typeof EmployeeRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/setup-guide': typeof SetupGuideRoute
  '/app': typeof AuthenticatedAppRoute
  '/licenses': typeof AuthenticatedLicensesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/mobile/android': typeof MobileAndroidRoute
  '/mobile/ios': typeof MobileIosRoute
  '/api/public/remote/accept': typeof ApiPublicRemoteAcceptRoute
  '/api/public/remote/pending': typeof ApiPublicRemotePendingRoute
  '/api/public/remote/register': typeof ApiPublicRemoteRegisterRoute
  '/api/public/remote/start': typeof ApiPublicRemoteStartRoute
  '/api/public/remote/stream': typeof ApiPublicRemoteStreamRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRoute
  '/download': typeof DownloadRoute
  '/employee': typeof EmployeeRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/setup-guide': typeof SetupGuideRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/licenses': typeof AuthenticatedLicensesRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/mobile/android': typeof MobileAndroidRoute
  '/mobile/ios': typeof MobileIosRoute
  '/api/public/remote/accept': typeof ApiPublicRemoteAcceptRoute
  '/api/public/remote/pending': typeof ApiPublicRemotePendingRoute
  '/api/public/remote/register': typeof ApiPublicRemoteRegisterRoute
  '/api/public/remote/start': typeof ApiPublicRemoteStartRoute
  '/api/public/remote/stream': typeof ApiPublicRemoteStreamRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/auth'
    | '/client'
    | '/download'
    | '/employee'
    | '/payment'
    | '/pricing'
    | '/services'
    | '/setup-guide'
    | '/app'
    | '/licenses'
    | '/tickets'
    | '/admin/audit'
    | '/mobile/android'
    | '/mobile/ios'
    | '/api/public/remote/accept'
    | '/api/public/remote/pending'
    | '/api/public/remote/register'
    | '/api/public/remote/start'
    | '/api/public/remote/stream'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/auth'
    | '/client'
    | '/download'
    | '/employee'
    | '/payment'
    | '/pricing'
    | '/services'
    | '/setup-guide'
    | '/app'
    | '/licenses'
    | '/tickets'
    | '/admin/audit'
    | '/mobile/android'
    | '/mobile/ios'
    | '/api/public/remote/accept'
    | '/api/public/remote/pending'
    | '/api/public/remote/register'
    | '/api/public/remote/start'
    | '/api/public/remote/stream'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/api-docs'
    | '/auth'
    | '/client'
    | '/download'
    | '/employee'
    | '/payment'
    | '/pricing'
    | '/services'
    | '/setup-guide'
    | '/_authenticated/app'
    | '/_authenticated/licenses'
    | '/_authenticated/tickets'
    | '/admin/audit'
    | '/mobile/android'
    | '/mobile/ios'
    | '/api/public/remote/accept'
    | '/api/public/remote/pending'
    | '/api/public/remote/register'
    | '/api/public/remote/start'
    | '/api/public/remote/stream'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiDocsRoute: typeof ApiDocsRoute
  AuthRoute: typeof AuthRoute
  ClientRoute: typeof ClientRoute
  DownloadRoute: typeof DownloadRoute
  EmployeeRoute: typeof EmployeeRoute
  PaymentRoute: typeof PaymentRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  SetupGuideRoute: typeof SetupGuideRoute
  MobileAndroidRoute: typeof MobileAndroidRoute
  MobileIosRoute: typeof MobileIosRoute
  ApiPublicRemoteAcceptRoute: typeof ApiPublicRemoteAcceptRoute
  ApiPublicRemotePendingRoute: typeof ApiPublicRemotePendingRoute
  ApiPublicRemoteRegisterRoute: typeof ApiPublicRemoteRegisterRoute
  ApiPublicRemoteStartRoute: typeof ApiPublicRemoteStartRoute
  ApiPublicRemoteStreamRoute: typeof ApiPublicRemoteStreamRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-guide': {
      id: '/setup-guide'
      path: '/setup-guide'
      fullPath: '/setup-guide'
      preLoaderRoute: typeof SetupGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/ios': {
      id: '/mobile/ios'
      path: '/mobile/ios'
      fullPath: '/mobile/ios'
      preLoaderRoute: typeof MobileIosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/android': {
      id: '/mobile/android'
      path: '/mobile/android'
      fullPath: '/mobile/android'
      preLoaderRoute: typeof MobileAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licenses': {
      id: '/_authenticated/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof AuthenticatedLicensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/remote/stream': {
      id: '/api/public/remote/stream'
      path: '/api/public/remote/stream'
      fullPath: '/api/public/remote/stream'
      preLoaderRoute: typeof ApiPublicRemoteStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/remote/start': {
      id: '/api/public/remote/start'
      path: '/api/public/remote/start'
      fullPath: '/api/public/remote/start'
      preLoaderRoute: typeof ApiPublicRemoteStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/remote/register': {
      id: '/api/public/remote/register'
      path: '/api/public/remote/register'
      fullPath: '/api/public/remote/register'
      preLoaderRoute: typeof ApiPublicRemoteRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/remote/pending': {
      id: '/api/public/remote/pending'
      path: '/api/public/remote/pending'
      fullPath: '/api/public/remote/pending'
      preLoaderRoute: typeof ApiPublicRemotePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/remote/accept': {
      id: '/api/public/remote/accept'
      path: '/api/public/remote/accept'
      fullPath: '/api/public/remote/accept'
      preLoaderRoute: typeof ApiPublicRemoteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedLicensesRoute: typeof AuthenticatedLicensesRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedLicensesRoute: AuthenticatedLicensesRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiDocsRoute: ApiDocsRoute,
  AuthRoute: AuthRoute,
  ClientRoute: ClientRoute,
  DownloadRoute: DownloadRoute,
  EmployeeRoute: EmployeeRoute,
  PaymentRoute: PaymentRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  SetupGuideRoute: SetupGuideRoute,
  MobileAndroidRoute: MobileAndroidRoute,
  MobileIosRoute: MobileIosRoute,
  ApiPublicRemoteAcceptRoute: ApiPublicRemoteAcceptRoute,
  ApiPublicRemotePendingRoute: ApiPublicRemotePendingRoute,
  ApiPublicRemoteRegisterRoute: ApiPublicRemoteRegisterRoute,
  ApiPublicRemoteStartRoute: ApiPublicRemoteStartRoute,
  ApiPublicRemoteStreamRoute: ApiPublicRemoteStreamRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
